version: "3.8"

services:
  smcroute:
    build:
      context: ./smcroute-docker 
    container_name: smcroute
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - smcroute:/etc/smc/smcroute.conf:ro
    cap_add:
      - NET_ADMIN
    tty: true

volumes:
  smcroute: 
    external: true
