name: Release General

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract ChangeLog entry ...
        # Hack to extract latest entry for body_path below
        run: |
          awk '/-----*/{if (x == 1) exit; x=1;next}x' ChangeLog.md \
              |head -n -1 > release.md
          cat release.md
      - name: Create release ...
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SMCRoute v${{ github.ref }}
          body_path: release.md
          draft: false
          prerelease: false
  tarball:
    name: Build and upload release tarball
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing dependencies ...
        run: |
          sudo modprobe ip_gre
          sudo apt-get -y update
          sudo apt-get -y install pkg-config libsystemd-dev libcap-dev tshark iptables valgrind
      - name: Creating Makefiles ...
        run: |
          ./autogen.sh
          ./configure --prefix= --enable-mrdisc --enable-test
      - name: Build release ...
        run: |
          sudo chmod a+rw /var/run/xtables.lock
          make release || (cat test/test-suite.log; false)
          ls -lF ../
          mkdir -p artifacts/
          mv ../*.tar.* artifacts/
      - name: Upload release artifacts ...
        uses: skx/github-action-publish-binaries@release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.release.outputs.release_id }}
          args: artifacts/*
